# Gunakan image resmi Nginx sebagai image dasar
FROM nginx:alpine

# Salin file HTML Anda ke dalam direktori web root Nginx
COPY . /usr/share/nginx/html

# Ekspos port 80 untuk mengakses web server
EXPOSE 80

# Jalankan server Nginx
CMD ["nginx", "-g", "daemon off;"]
